<select id="flight" name="flight" class="dropdown_field_txt" style="width:11em;">
	<option value="Q5"> 40 Mile Air</option>
	<option value="7L"> AB Airlines</option>
	<option value="M3"> ABSA Cargo - Aerolinhas Breseleiras SA</option>
	<option value="ZA"> AccessAir</option>
	<option value="VX"> ACES Colombia</option>
	<option value="XQ"> Action Airlines</option>
	<option value="WZ"> Acvilla Air - Aor Romanian Carrier</option>
	<option value="ZY"> Ade Air Albania</option>
	<option value="JP"> Adria Airways</option>
	<option value="4G"> Advance Leasing</option>
	<option value="RE"> Aer Arann</option>
	<option value="EI"> Aer Lingus</option>
	<option value="E4"> Aero Asia International</option>
	<option value="N6"> Aero Continente</option>
	<option value="NU"> Aero Contractors Company of Nigeria - ACN</option>
	<option value="YP"> Aero Lloyd</option>
	<option value="UJ"> Aero Santa</option>
	<option value="W4"> Aero Services Executive</option>
	<option value="Z9"> Aero Zambia</option>
	<option value="JR"> Aerocalifornia</option>
	<option value="QA"> Aerocaribe</option>
	<option value="P2"> Aerocondor</option>
	<option value="SX"> Aeroexo - Aero Ejectivo</option>
	<option value="SU"> Aeroflot Russian International Airlines</option>
	<option value="AR"> Aerolineas Argentinas</option>
	<option value="N2"> Aerolineas Internacionales</option>
	<option value="EX"> Aerolineas Santo Domingo</option>
	<option value="P4"> Aerolineas Sosa</option>
	<option value="4Q"> AeroLyon</option>
	<option value="BQ"> Aeromar</option>
	<option value="VW"> Aeromar Airlines</option>
	<option value="AM"> Aeromexico</option>
	<option value="QO"> Aeromexpress</option>
	<option value="WL"> Aeroperlas (Apair - Aerolineas Pacificio Atlantico)</option>
	<option value="PL"> Aeroperu</option>
	<option value="VH"> Aeropostal</option>
	<option value="P5"> Aerorepublica Colombia</option>
	<option value="BF"> Aeroservice</option>
	<option value="6N"> Aerosucre</option>
	<option value="5L"> Aerosur</option>
	<option value="VV"> Aerosweet Airlines</option>
	<option value="ZL"> Affertair</option>
	<option value="3L"> Africa West</option>
	<option value="OY"> African International Airways</option>
	<option value="ZF"> Aiborne of Sweden</option>
	<option value="LQ"> Aipac Airlines</option>
	<option value="DP"> Air 2000</option>
	<option value="RK"> Air Afrique</option>
	<option value="8S"> Air Alaska Cargo</option>
	<option value="H7"> Air Alfa</option>
	<option value="AH"> Air Algerie</option>
	<option value="3J"> Air Alliance</option>
	<option value="TD"> Air Anatolia</option>
	<option value="FQ"> Air Aruba</option>
	<option value="AK"> Air Asia</option>
	<option value="CC"> Air Atlanta - Atlanta Icelandic Air Transport</option>
	<option value="9A"> Air Atlantic</option>
	<option value="LU"> Air Atlantic Dominicana</option>
	<option value="QD"> Air Atlantic Spain</option>
	<option value="UU"> Air Austral</option>
	<option value="BT"> Air Baltic</option>
	<option value="ZX"> Air BC</option>
	<option value="AJ"> Air Belgium International</option>
	<option value="AB"> Air Berlin</option>
	<option value="JA"> Air Bosna</option>
	<option value="KF"> Air Botnia</option>
	<option value="BP"> Air Botswana</option>
	<option value="2J"> Air Burkina</option>
	<option value="TY"> Air Caledonie</option>
	<option value="SB"> Air Caledonie International</option>
	<option value="AC"> Air Canada</option>
	<option value="WS"> Air Caraibes</option>
	<option value="3K"> Air Cargo Express</option>
	<option value="C2"> Air Carribean</option>
	<option value="XC"> Air Carribean - CLTM Airlines</option>
	<option value="CV"> Air Chathams</option>
	<option value="CA"> Air China</option>
	<option value="4F"> Air City</option>
	<option value="2Z"> Air Comet</option>
	<option value="AG"> Air Contracors</option>
	<option value="YN"> Air Creebec</option>
	<option value="2N"> Air d'Ayiti</option>
	<option value="C7"> Air Direct</option>
	<option value="DY"> Air Djibouti - Red Sea Airlines</option>
	<option value="EN"> Air Dolomiti</option>
	<option value="K5"> Air East Africa</option>
	<option value="UX"> Air Europa</option>
	<option value="PE"> Air Europe Italy</option>
	<option value="FZ"> Air Facilities</option>
	<option value="PC"> Air Fiji (Fiji Air Services)</option>
	<option value="FD"> Air Florida Express</option>
	<option value="GS"> Air Foyle</option>
	<option value="AF"> Air France</option>
	<option value="GN"> Air Gabon</option>
	<option value="DA"> Air Georgia</option>
	<option value="GB"> Air Glaciers</option>
	<option value="JG"> Air Greece</option>
	<option value="TX"> Air Guadeloupe</option>
	<option value="GG"> Air Holland</option>
	<option value="LD"> Air Hong Kong</option>
	<option value="NY"> Air Iceland - Flugfelag Islands</option>
	<option value="AI"> Air India</option>
	<option value="3H"> Air Inuit</option>
	<option value="VU"> Air ivoire</option>
	<option value="JM"> Air Jamaica</option>
	<option value="BC"> Air Jet</option>
	<option value="9Y"> Air Kazakstan</option>
	<option value="QP"> Air Kenya Aviation</option>
	<option value="JS"> Air Koryo</option>
	<option value="WJ"> Air Labrador - Labrador Airways</option>
	<option value="UL"> Air Lanka</option>
	<option value="IJ"> Air Liberte</option>
	<option value="DR"> Air Link</option>
	<option value="TT"> Air Lithuania - Aviakompanija Lietuva</option>
	<option value="FU"> Air Littoral</option>
	<option value="NX"> Air Macau</option>
	<option value="MD"> Air Madagascar</option>
	<option value="QM"> Air Malawi</option>
	<option value="L6"> Air Maldives</option>
	<option value="L9"> Air Mali</option>
	<option value="KM"> Air Malta</option>
	<option value="6T"> Air mandalay</option>
	<option value="CW"> Air Marshall Islands</option>
	<option value="MR"> Air Mauritanie</option>
	<option value="MK"> Air Mauritius</option>
	<option value="9U"> Air Moldova</option>
	<option value="3R"> Air Moldova International</option>
	<option value="F8"> Air Montreal</option>
	<option value="SW"> Air Namibia</option>
	<option value="ON"> Air Nauru</option>
	<option value="5T"> Air Negril</option>
	<option value="NZ"> Air New Zealand</option>
	<option value="NM"> Air New Zealand Link / Mount Cook Airlines</option>
	<option value="EL"> Air Nippon</option>
	<option value="PX"> Air Niugini</option>
	<option value="4N"> Air North Charter</option>
	<option value="TL"> Air North Regional</option>
	<option value="YW"> Air Nostrum</option>
	<option value="QK"> Air Nova</option>
	<option value="9Q"> Air One</option>
	<option value="AP"> Air One</option>
	<option value="GX"> Air Ontario</option>
	<option value="UT"> Air Orient</option>
	<option value="8K"> Air Ostrava</option>
	<option value="FJ"> Air Pacific</option>
	<option value="2P"> Air Philippines</option>
	<option value="OB"> Air Plus</option>
	<option value="DG"> Air Provence Interionational</option>
	<option value="GZ"> Air Roratonga</option>
	<option value="ZJ"> Air Routing International</option>
	<option value="OJ"> Air Saint Barthelemy (Barths Aviation)</option>
	<option value="S6"> Air Saint Martin</option>
	<option value="PJ"> Air Saint Pierre</option>
	<option value="ZP"> Air Saint Thomas</option>
	<option value="HM"> Air Seychelles</option>
	<option value="BM"> Air Sicilia</option>
	<option value="4D"> Air Sinai</option>
	<option value="GM"> Air Slovakia</option>
	<option value="CT"> Air Sofia</option>
	<option value="GO"> Air Stord</option>
	<option value="0O"> Air Sultan</option>
	<option value="YI"> Air Sunshine</option>
	<option value="VT"> Air Tahiti</option>
	<option value="TN"> Air Tahiti NUI</option>
	<option value="TC"> Air Tanzania</option>
	<option value="8W"> Air Team</option>
	<option value="SH"> Air Toulouse International</option>
	<option value="TS"> Air Transat</option>
	<option value="8C"> Air Transport International - ATI</option>
	<option value="8T"> Air Trindi</option>
	<option value="6U"> Air Ukraine - Avialinii Ukrainy</option>
	<option value="3N"> Air Urga</option>
	<option value="DO"> Air Vallee</option>
	<option value="NF"> Air Vanuatu</option>
	<option value="6V"> Air Vegas</option>
	<option value="DO"> Air Virginia</option>
	<option value="XR"> Air Wings</option>
	<option value="ZT"> Air Zambezi</option>
	<option value="A9"> Air Zena</option>
	<option value="UM"> Air Zimbabwe</option>
	<option value="GB"> Airborne Express - ABX Air</option>
	<option value="4C"> Aires - Aerovias de Integracion Regional</option>
	<option value="C4"> Airlines of Carriacou</option>
	<option value="RT"> Airlines of South Australia</option>
	<option value="ND"> Airlink</option>
	<option value="ID"> Airmax Airlines</option>
	<option value="VZ"> Airtours International Airways</option>
	<option value="FL"> Airtran Airways</option>
	<option value="E9"> AJT Air International</option>
	<option value="6L"> Aklak</option>
	<option value="AS"> Alaska Airlines</option>
	<option value="KO"> Alaska Central Express - ACE</option>
	<option value="UI"> Alaska Seaplane Service</option>
	<option value="LV"> Albanian Airlines MAK</option>
	<option value="D4"> Alidaunia</option>
	<option value="AZ"> Alitalia</option>
	<option value="XM"> Alitalia Express</option>
	<option value="RD"> Alitalia Team</option>
	<option value="NH"> All Nippon Airways</option>
	<option value="LL"> Allegro Air</option>
	<option value="CD"> Alliance Air</option>
	<option value="3A"> Alliance Airlines</option>
	<option value="LM"> ALM Antillean Airlines</option>
	<option value="AQ"> Aloha Airlines</option>
	<option value="WP"> Aloha Island Air</option>
	<option value="E8"> Alpi Eagles</option>
	<option value="5A"> Alpine Air</option>
	<option value="DY"> Alyemen - Airlines of Yemen</option>
	<option value="9V"> AMC Aviation</option>
	<option value="HP"> America West Airlines</option>
	<option value="AA"> American Airlines</option>
	<option value="M6"> AmeriJet International</option>
	<option value="MO"> Amiri Flight (Abu Dhabi)</option>
	<option value="8G"> Angel Airlines</option>
	<option value="TI"> Angkor Airlines</option>
	<option value="AN"> Ansett Australia</option>
	<option value="ZQ"> Ansett New Zealnad</option>
	<option value="IW"> AOM French Airlines</option>
	<option value="7P"> APA Internacional</option>
	<option value="4A"> Ararat Avia</option>
	<option value="Y5"> Arax Airways</option>
	<option value="F5"> Archana Airways</option>
	<option value="5F"> Arctic Circle Air Service</option>
	<option value="7S"> Arctic Transportation Services</option>
	<option value="FG"> Ariana Afghan Airlines</option>
	<option value="D4"> Aries del Sur</option>
	<option value="IZ"> Arkia Israeli Airlines</option>
	<option value="R3"> Armenian Airlines</option>
	<option value="A8"> ARPA - Aerolineas Paraguayas</option>
	<option value="JW"> Arrow Air</option>
	<option value="EV"> ASA / Delta Connection - Atlantic Southeast Airlines</option>
	<option value="R7"> ASERCA - Aeroservicios Carabobo</option>
	<option value="HJ"> Asian Express Airlines</option>
	<option value="OZ"> Asiana Airlines</option>
	<option value="AD"> Aspen Mountain Air</option>
	<option value="OI"> Aspiring Air</option>
	<option value="A7"> Astanair Kazakstan</option>
	<option value="TZ"> ATA - American Trans Air</option>
	<option value="2B"> ATA Aerocondor</option>
	<option value="9T"> Athabaska Airways</option>
	<option value="3G"> Atlant Soyuz Airlines</option>
	<option value="RC"> Atlantic Airways</option>
	<option value="DH"> Atlantic Coast Airlines</option>
	<option value="5Y"> Atlas Air</option>
	<option value="V8"> ATRAN - Aviatrans Cargo Airlines</option>
	<option value="IQ"> Augsburg Airways</option>
	<option value="GR"> Aurigny Air Services</option>
	<option value="NO"> Aus Air</option>
	<option value="7V"> Austin Express</option>
	<option value="AU"> Austral Lineas Aereas</option>
	<option value="XM"> Australian Air Express</option>
	<option value="OS"> Austrian Airlines</option>
	<option value="OT"> Avant Airlines - Linheas Aereas Chilenas</option>
	<option value="J6"> Avcom - Aviation Commercial</option>
	<option value="VE"> Avensa</option>
	<option value="RX"> Avia Express</option>
	<option value="AO"> Aviaco</option>
	<option value="6A"> Aviacsa</option>
	<option value="AD"> Avialeasing</option>
	<option value="AV"> Avianca</option>
	<option value="J5"> Aviaprima - Sochi Airlines</option>
	<option value="GU"> Aviateca</option>
	<option value="M4"> Avioimpex Makedonija Airways</option>
	<option value="3B"> AVIOR - Aviones de Oriente</option>
	<option value="DF"> Aviosarda Airlines</option>
	<option value="J2"> Azerbaijan Airlines - AZAL Avia</option>
	<option value="ZS"> Azzurra Air</option>
	<option value="BF"> B Airways</option>
	<option value="UP"> Bahamasair</option>
	<option value="X3"> Baikal Airlines</option>
	<option value="8Q"> Baker Aviation</option>
	<option value="BB"> Balair/CTA Leisure</option>
	<option value="LZ"> Balkan Bulgarian Airlines</option>
	<option value="PG"> Bangkok Airways</option>
	<option value="B4"> Bankair</option>
	<option value="5E"> BASE Airlines</option>
	<option value="V9"> Bashkirian Airlines - Bashkirskjie Avialinii</option>
	<option value="8W"> BAX Global</option>
	<option value="6B"> Baxter Aviation</option>
	<option value="JV"> Bearskin Airlines</option>
	<option value="BL"> Belair Ile de France</option>
	<option value="B2"> Belavia</option>
	<option value="7G"> Bellair</option>
	<option value="B3"> Bellview Airlines</option>
	<option value="CH"> Bemidji Airlines</option>
	<option value="8E"> Bering Air</option>
	<option value="J8"> Berjaya Air</option>
	<option value="B4"> Bhoja Airlines</option>
	<option value="GQ"> Big Sky Airlines</option>
	<option value="BG"> Biman Bangladesh Airlines</option>
	<option value="NT"> Binter Canarias</option>
	<option value="AX"> Binter Mediterraneo</option>
	<option value="BP"> Bleu Panorama Airlines</option>
	<option value="BO"> Bouraq Indonesia Airlines</option>
	<option value="BU"> Braathens</option>
	<option value="6E"> Braathens Malmo Aviation</option>
	<option value="DB"> Britair</option>
	<option value="BY"> Britannia Airways</option>
	<option value="BN"> Britannia Airways Deutschland</option>
	<option value="BA"> British Airways</option>
	<option value="BS"> British International Helicopters</option>
	<option value="KJ"> British Mediterranean Airways</option>
	<option value="BD"> British Midland Airways</option>
	<option value="TH"> British Regional Airlines</option>
	<option value="VF"> British World Airlines</option>
	<option value="6B"> Brittania Airways Sweden</option>
	<option value="J4"> Buffalo Airways</option>
	<option value="HQ"> Business Express Airlines - BEX</option>
	<option value="BW"> BWIA International Airways</option>
	<option value="5C"> CAL - Cargo Airlines</option>
	<option value="MO"> Calm Air</option>
	<option value="R9"> Camai Air</option>
	<option value="UY"> Cameroon Airlines</option>
	<option value="2T"> Canada 3000</option>
	<option value="CP"> Canadian Airlies International</option>
	<option value="FW"> Canarias Regional Air</option>
	<option value="9K"> Cape Air</option>
	<option value="6C"> Cape Smythe Air Service</option>
	<option value="NS"> Cape York Air</option>
	<option value="PT"> Capital Cargo International Airlines</option>
	<option value="NN"> Cardinal Airlines</option>
	<option value="CV"> Cargolux Airlines International</option>
	<option value="K7"> Carib Aviation</option>
	<option value="XC"> Carribean Air Transport - CLTM Airlines</option>
	<option value="XP"> Casino Express</option>
	<option value="CX"> Cathay Pacific Airways</option>
	<option value="KX"> Cayman Airways</option>
	<option value="5J"> Cebu Pacific Air</option>
	<option value="9M"> Central Mountain Air</option>
	<option value="GC"> Centralafrican Airlines</option>
	<option value="M6"> Chalair</option>
	<option value="OP"> Chalk's International Airline</option>
	<option value="WE"> Challenge Air Cargo</option>
	<option value="MG"> Champion Air</option>
	<option value="2Z"> Changan Airlines</option>
	<option value="LS"> Channel Express</option>
	<option value="H6"> Chelal - Chelyabinsk Air Enterprise</option>
	<option value="C8"> Chicago Express Airwasy (ATA Connection)</option>
	<option value="CI"> China Airlines</option>
	<option value="MU"> China Eastern Airlines</option>
	<option value="F6"> China National Aviation Corporation - CNAC</option>
	<option value="CJ"> China Northern Airlines</option>
	<option value="WH"> China Northwest Airlines</option>
	<option value="CZ"> China Southern Airlines</option>
	<option value="SZ"> China Southwest Airlines</option>
	<option value="XO"> China Xinjiang Airlines</option>
	<option value="3Q"> China Yunnan Airlines</option>
	<option value="X7"> Chitaavia</option>
	<option value="QI"> Cimber Air</option>
	<option value="FO"> Circle Air Freight</option>
	<option value="C9"> Cirrus Airlines</option>
	<option value="H2"> City Bird Airlines</option>
	<option value="FD"> Cityflyer</option>
	<option value="WX"> Cityjet</option>
	<option value="C9"> CLA Air Transport</option>
	<option value="BX"> Coast Air</option>
	<option value="DQ"> Coastal Air Transport</option>
	<option value="9L"> Colgan Air</option>
	<option value="CA"> Color Air</option>
	<option value="7C"> Columbia Pacific Airlines</option>
	<option value="MN"> Comair</option>
	<option value="OH"> Comair/Delta Connection</option>
	<option value="E9"> Compagnie Africaine d'Aviation</option>
	<option value="XK"> Compagnie Corse Mediterranee</option>
	<option value="DE"> Condor</option>
	<option value="EO"> Congo Airlines - CAL</option>
	<option value="CQ"> Constellation International Airlines</option>
	<option value="V8"> Contact Air</option>
	<option value="CO"> Continental Airlines</option>
	<option value="PC"> Continental Airways</option>
	<option value="CS"> Continental Micronesia</option>
	<option value="CM"> COPA Panama</option>
	<option value="3C"> Corporate Airlines</option>
	<option value="SS"> Corsair</option>
	<option value="ZE"> Cosmos Air</option>
	<option value="XL"> Country Connection Airlines</option>
	<option value="7C"> Coyne Airways</option>
	<option value="OR"> Crimea Air</option>
	<option value="OU"> Croatia Airlines</option>
	<option value="X5"> Cronus Airlines</option>
	<option value="LX"> Crossair</option>
	<option value="QE"> Crossair Europe</option>
	<option value="OK"> CSA Czech Airlines - Ceske Aerolinie</option>
	<option value="CU"> Cubana</option>
	<option value="DG"> Custom Air Transport</option>
	<option value="CY"> Cyprus Airways</option>
	<option value="D3"> Daallo Airlines</option>
	<option value="D2"> Damania Airways</option>
	<option value="DX"> Danish Air Transport</option>
	<option value="AW"> DAS - Dirgantara Air Service</option>
	<option value="SE"> DAS Air Cargo</option>
	<option value="2G"> Debonair Airways</option>
	<option value="DL"> Delta Airlines</option>
	<option value="3D"> Denim Air</option>
	<option value="DI"> Deutsche BA</option>
	<option value="DV"> Deutsche Rettungsflugwacht</option>
	<option value="DS"> DHL Aero Expreso</option>
	<option value="ER"> DHL Airways</option>
	<option value="Z8"> DHL de Guatemala</option>
	<option value="ES"> DHL International EC</option>
	<option value="9X"> Diamond International Airlines</option>
	<option value="D8"> Diamond Sakha Airlines</option>
	<option value="D7"> Dinar Lineas Aereas</option>
	<option value="Z6"> Dnieproavia Aviation Company</option>
	<option value="YU"> Dominair - Aerolineas Dominicanas</option>
	<option value="E3"> Domodedovo Airlines</option>
	<option value="D9"> Donavia</option>
	<option value="7D"> Donbass Eastern Ukranian Airlines</option>
	<option value="KA"> Dragonair (Hong Kong Dragon Airlines)</option>
	<option value="5D"> Dutchbird</option>
	<option value="ZN"> Eagle Airlines</option>
	<option value="Y4"> Eagle Aviation</option>
	<option value="FE"> Eagle Canyon Airlines</option>
	<option value="P7"> East Line Airlines</option>
	<option value="DK"> Eastland Air - Moores Air Charter</option>
	<option value="W9"> Eastwind Airlines</option>
	<option value="9W"> Eastwind Airlines - The Bee Line</option>
	<option value="U2"> EasyJet Airlines</option>
	<option value="BH"> Easyjet Switzerland</option>
	<option value="EU"> Ecuatoriana</option>
	<option value="ED"> Edelweiss Air</option>
	<option value="MS"> Egypt Air</option>
	<option value="LY"> El Al Israel Airlines</option>
	<option value="S8"> ELK Airways Estonian Aviation - Eesti Lennukompanii</option>
	<option value="G3"> Emerald Airways</option>
	<option value="EB"> Emery Worldwide Airlines</option>
	<option value="EK"> Emirates</option>
	<option value="EM"> Empire Airlines</option>
	<option value="5Z"> Enkor</option>
	<option value="8H"> Equaflight Service</option>
	<option value="7H"> ERA Aviation</option>
	<option value="OV"> Estonian Air</option>
	<option value="ET"> Ethiopian Airlines</option>
	<option value="RN"> Euralair International</option>
	<option value="F4"> Eureca</option>
	<option value="UI"> Eurocypria Airlines</option>
	<option value="GJ"> Eurofly</option>
	<option value="Y6"> Europe Elite</option>
	<option value="QY"> European Air Transport - EAT</option>
	<option value="EA"> European Regions Airlines - ERA</option>
	<option value="MY"> Euroscot Express Airways</option>
	<option value="EW"> Eurowings</option>
	<option value="BR"> EVA Air</option>
	<option value="EZ"> Evergreen International Airlines</option>
	<option value="MB"> Execaire Aviation</option>
	<option value="5W"> Executive Express</option>
	<option value="1L"> Executive Jet Aviation</option>
	<option value="FO"> Expedition Airways</option>
	<option value="8D"> Expo Airlines</option>
	<option value="EO"> Express One International</option>
	<option value="IH"> Falcon Air</option>
	<option value="F2"> Falcon Air Express</option>
	<option value="FC"> Falcon Express Air Cargo</option>
	<option value="EF"> Far Eastern Air Transport</option>
	<option value="UD"> Fast Air</option>
	<option value="CF"> Faucett</option>
	<option value="2D"> Federico II Airways</option>
	<option value="FM"> FedEx - Federall Express</option>
	<option value="FX"> FedEx - Federall Express</option>
	<option value="HG"> Fika Salaama Airlines</option>
	<option value="FB"> Fine Airlines</option>
	<option value="AY"> Finnair</option>
	<option value="7F"> First Air</option>
	<option value="8F"> Fischer Air</option>
	<option value="IX"> Flandre Air</option>
	<option value="YC"> Flight West Airlines</option>
	<option value="RF"> Florida West Airlines</option>
	<option value="FT"> Fly FTI</option>
	<option value="MT"> Flying Colours Airlines</option>
	<option value="F3"> Flying Enterprise</option>
	<option value="BN"> Forward Air Int'l Airlines</option>
	<option value="HK"> Four Star Air Cargo</option>
	<option value="F9"> Frontier Airlines</option>
	<option value="F9"> Frontier Commuter - ITR Airlines</option>
	<option value="2F"> Frontier Flying Service</option>
	<option value="Y7"> FS Air Service</option>
	<option value="IV"> Fujian Airlines</option>
	<option value="FH"> Futura International</option>
	<option value="GA"> Garuda Indonesia</option>
	<option value="GT"> GB Airways</option>
	<option value="GR"> Gemini Air Cargo</option>
	<option value="GR"> Gemini Airlines</option>
	<option value="3P"> Georgian Airlines</option>
	<option value="ST"> Germania</option>
	<option value="GP"> Gestair Executive Jet</option>
	<option value="GH"> Ghana Airways</option>
	<option value="9C"> Gill Airways</option>
	<option value="Z5"> GMG Airlines</option>
	<option value="OG"> GO Fly</option>
	<option value="GK"> Go One Airways</option>
	<option value="DC"> Golden Air</option>
	<option value="GW"> Golden West Airlines</option>
	<option value="YD"> Gomelavia</option>
	<option value="UR"> Government of Brunei - His Majesty The Sultan's Flight</option>
	<option value="8G"> GP Express Airlines</option>
	<option value="GS"> Grant Aviation</option>
	<option value="GB"> Great Barrier Airlines</option>
	<option value="GL"> Greenlandair - Gronlandsfly</option>
	<option value="FB"> Guard Air</option>
	<option value="G8"> Gujarat Airways</option>
	<option value="GF"> Gulf Air</option>
	<option value="3M"> Gulfstream International Airlines</option>
	<option value="GY"> Guyana Airways</option>
	<option value="H6"> Hageland Aviation Services</option>
	<option value="HR"> Hahn Air Businesslines</option>
	<option value="H4"> Hainan Airlines</option>
	<option value="7A"> Haines Airways</option>
	<option value="9F"> Haiti Air International</option>
	<option value="HG"> Haiti International Airlines</option>
	<option value="HF"> Hapag Lloyd</option>
	<option value="HB"> Harbor Airlines</option>
	<option value="H3"> Harbour Air</option>
	<option value="JH"> Harlequin Air</option>
	<option value="HA"> Hawaiian Airlines</option>
	<option value="ZL"> Hazelton Airlines</option>
	<option value="NP"> Heavylift Cargo Airlines</option>
	<option value="2Y"> Helenair</option>
	<option value="LE"> Helgoland Airlines</option>
	<option value="YO"> Heli Air Monaco</option>
	<option value="EC"> Heli Inter</option>
	<option value="5H"> Heli Trans</option>
	<option value="YQ"> Helicopterservice Euro Air</option>
	<option value="JB"> Helijet Airways</option>
	<option value="L5"> Helikopter Service</option>
	<option value="H9"> Helisul</option>
	<option value="H9"> Helisul Taxi Aereo</option>
	<option value="UV"> Helisureste</option>
	<option value="DU"> Hemus Air</option>
	<option value="UD"> Hex'Air</option>
	<option value="HS"> Highland Air</option>
	<option value="8R"> Highland Airways</option>
	<option value="LF"> Hinduja Cargo Services - Lufthansa Cargo India</option>
	<option value="HD"> Hokkaido International Airlines - Air Do</option>
	<option value="QX"> Horizon Air/Alaska Airlines Commuter</option>
	<option value="YK"> Horizon Airlines</option>
	<option value="IB"> Iberia</option>
	<option value="TY"> Iberostar Airlines</option>
	<option value="TY"> Iberworld Airlines</option>
	<option value="C3"> ICAR Airlines</option>
	<option value="1I"> Icaro</option>
	<option value="FI"> Icelandair</option>
	<option value="LS"> Iliamna Air taxi</option>
	<option value="IK"> Improtex - Imair</option>
	<option value="VQ"> Impulse Airlines</option>
	<option value="IC"> Indian Airlines</option>
	<option value="RS"> Inercontinental Colombia</option>
	<option value="IM"> Intensive Air</option>
	<option value="D6"> Inter Air Lines</option>
	<option value="Q9"> Interbrasil Star</option>
	<option value="U5"> International Business Air</option>
	<option value="IR"> Iran Air (Iran National Airlines)</option>
	<option value="IA"> Iraqi Airways</option>
	<option value="G5"> Island Air</option>
	<option value="IS"> Island Air</option>
	<option value="DG"> Island Airlines</option>
	<option value="CN"> Islands Nationair</option>
	<option value="HH"> Islandsflug - Icebird Airline</option>
	<option value="5Y"> Isles of Scilly Skybus</option>
	<option value="6H"> Israir</option>
	<option value="IL"> Istanbul Airlines</option>
	<option value="5W"> ITA Itapemirim Transportes Aereos</option>
	<option value="B8"> Italair</option>
	<option value="JC"> JAL Express</option>
	<option value="JZ"> Japan Air Charter</option>
	<option value="3X"> Japan Air Commuter</option>
	<option value="JL"> Japan Air Lines</option>
	<option value="JD"> Japan Air System</option>
	<option value="EG"> Japan Asia Airways</option>
	<option value="NU"> Japan Transocean Air</option>
	<option value="JU"> JAT Yugoslav Airlines</option>
	<option value="JY"> Jersey European Airways</option>
	<option value="9W"> Jet Airways</option>
	<option value="PP"> Jet Aviation Business Jets</option>
	<option value="K8"> Kaliningrad Avia Entreprise</option>
	<option value="KT"> Kampuchea Airlines</option>
	<option value="2U"> Karat - Aviacompany Karat</option>
	<option value="KV"> Kavminvodyavia</option>
	<option value="XC"> KD Air</option>
	<option value="KD"> Kendell Airlines (Australia)</option>
	<option value="M5"> Kenmore Air</option>
	<option value="4K"> Kenn Borek Air</option>
	<option value="KQ"> Kenya Airways</option>
	<option value="BZ"> Keystone Air Services</option>
	<option value="H8"> Khabarovsk Aviation</option>
	<option value="X9"> Khors Air</option>
	<option value="YK"> Kibris Turkish Airlines - KTHY (Cyprus Turkish Airlines)</option>
	<option value="KG"> King Island Airlines</option>
	<option value="KR"> Kitty Hawk Air Cargo</option>
	<option value="KR"> Kitty hawk International</option>
	<option value="KP"> Kiwi International Airlines</option>
	<option value="WA"> KLM Cityhopper</option>
	<option value="XT"> KLM Exel</option>
	<option value="KL"> KLM Royal Dutch Airlines</option>
	<option value="UK"> KLM UK</option>
	<option value="7K"> Kogalymavia</option>
	<option value="KE"> Korean Air</option>
	<option value="7B"> Kras Air - Krasnoyarskavia</option>
	<option value="K4"> Kronflyg</option>
	<option value="GW"> Kuban Airlines</option>
	<option value="KU"> Kuwait Airways</option>
	<option value="K2"> Kyrgystan Airlines</option>
	<option value="7W"> La Ronge Aviation Services - Air Sask Aviation</option>
	<option value="LB"> LAB - Lloyd Aereo Boliviano</option>
	<option value="JF"> LAB Flying Service - Alaska Airlines Commuter</option>
	<option value="LR"> LACSA - Lineasaereas Costarricenses SA</option>
	<option value="UC"> LADECO - Linea Aerea Del Cobre</option>
	<option value="UC"> LADECO Cargo</option>
	<option value="KG"> LAI - Linea Aerea IAACA</option>
	<option value="6F"> Laker Airways</option>
	<option value="7Z"> Laker Airways (Bahamas)</option>
	<option value="TM"> LAM - Linheas Aereas de Mocambique</option>
	<option value="LA"> LAN Chile</option>
	<option value="QV"> Lao Aviation</option>
	<option value="L7"> Laoag International</option>
	<option value="MJ"> LAPA - Lineas Aereas Privadas Argentinas</option>
	<option value="L8"> Laparkan Airlines</option>
	<option value="J6"> Larry's Flying Service</option>
	<option value="6G"> Las Vegas Airlines</option>
	<option value="KZ"> LASER - Lineas Aereas de Servicio Ejecutivo Regional</option>
	<option value="KY"> LASTP</option>
	<option value="QJ"> Latpass Airlines</option>
	<option value="NG"> Lauda Air</option>
	<option value="L4"> Lauda Air Italy</option>
	<option value="LQ"> Lebanese Air Transport</option>
	<option value="HE"> LGW - Luftfahrt Gesellschaft Walter</option>
	<option value="LI"> LIAt - The Carribean Airline</option>
	<option value="LN"> Libyan Arab Airlines</option>
	<option value="XU"> Link Airways of Australia</option>
	<option value="TE"> Lithuanian Airlines</option>
	<option value="LO"> LOT Polish Airlines</option>
	<option value="T2"> Lotus Air</option>
	<option value="4J"> Loveair</option>
	<option value="XO"> LTE International Airways</option>
	<option value="LT"> LTU International Airways</option>
	<option value="LH"> Lufthansa</option>
	<option value="LH"> Lufthansa Cargo Airlines</option>
	<option value="CL"> Lufthansa Cityline</option>
	<option value="LG"> Luxair</option>
	<option value="L2"> Lynden Air Cargo</option>
	<option value="CC"> Macair Airlines</option>
	<option value="SX"> Macedonian Airlines</option>
	<option value="IN"> Macedonian Airlines - Makedonski Aviotransport</option>
	<option value="DM"> Maersk Air</option>
	<option value="VB"> Maersk Air (UK)</option>
	<option value="FS"> MAF Australia - Missionary Aviation Fellowship</option>
	<option value="3A"> Mafira Air</option>
	<option value="H5"> Magadan Airlines</option>
	<option value="M2"> Mahfooz Aviation</option>
	<option value="MA"> Malev - Hungarian Airlines</option>
	<option value="R5"> Malta Air Charter</option>
	<option value="AE"> Mandarin Airlines</option>
	<option value="JE"> Manx Airlines</option>
	<option value="M2"> Mario's Air</option>
	<option value="KN"> Maroomba Airlines</option>
	<option value="MP"> Martinair</option>
	<option value="MH"> MAS - Malaysian Airlines System</option>
	<option value="MY"> Mas Air Cargo</option>
	<option value="MW"> Maya Island Air</option>
	<option value="EY"> Mayan World Airlines</option>
	<option value="CG"> MBA Air</option>
	<option value="KR"> MDA Airlines</option>
	<option value="ME"> MEA - Middle East Airlines</option>
	<option value="M8"> Med Airlines</option>
	<option value="MG"> Mediterranean Air Service</option>
	<option value="BX"> Mercury Air Cargo</option>
	<option value="IG"> Meridiana</option>
	<option value="MZ"> Merpati Nusantara Airlines</option>
	<option value="YV"> Mesa Airlines</option>
	<option value="OW"> Metavia Airlines</option>
	<option value="MX"> Mexicana</option>
	<option value="GJ"> Mexicargo</option>
	<option value="GL"> Miami Air International</option>
	<option value="OM"> MIAT Mongolian Airlines</option>
	<option value="JI"> Midway Airlines</option>
	<option value="YX"> Midwest Express Airlines</option>
	<option value="2Q"> Millair</option>
	<option value="Q2"> Minerva Airlines</option>
	<option value="N3"> Miravia</option>
	<option value="7G"> MK Airlines</option>
	<option value="W4"> MN Aviation</option>
	<option value="MB"> MNG Airlines Cargo</option>
	<option value="M9"> Modiluft</option>
	<option value="2M"> Moldavian Airlines</option>
	<option value="ZB"> Monarch Airlines</option>
	<option value="1I"> Montenegro Airlines</option>
	<option value="ZR"> Muk Air</option>
	<option value="Q4"> Mustique Airways (Air Saint Vincent)</option>
	<option value="HC"> Naske Air</option>
	<option value="N4"> National Airlines</option>
	<option value="YJ"> National Airways Corporation - NAC</option>
	<option value="NC"> National Jet Systems</option>
	<option value="N5"> Nations Air</option>
	<option value="CE"> Nationwide Airlines</option>
	<option value="XV"> Nature Island Express</option>
	<option value="3Z"> Necon Air</option>
	<option value="D5"> NEPC Airlines</option>
	<option value="EJ"> New England Airlines</option>
	<option value="HD"> New York Helicopter</option>
	<option value="6Y"> NICA - Nicaraguenses de Aviacion</option>
	<option value="JX"> Nice Helicopteres</option>
	<option value="WT"> Nigeria Airways</option>
	<option value="KZ"> Nippon Cargo Airlines</option>
	<option value="JH"> Nordeste - Linhas Aereas regionais</option>
	<option value="ID"> Normandie Aviation</option>
	<option value="XG"> North American Airlines</option>
	<option value="N9"> North Coast Aviation</option>
	<option value="VL"> North Vancouver Airliners</option>
	<option value="HW"> North Wright Airways</option>
	<option value="NE"> Northeast Airlines</option>
	<option value="NC"> Northern Air Cargo - NAC</option>
	<option value="4R"> Northern Thunderbird Air</option>
	<option value="NW"> Northwest Airlines</option>
	<option value="9E"> Northwest Airlink/Express Airlines</option>
	<option value="XJ"> Northwest Airlink/Mesaba Airlines</option>
	<option value="J3"> Northwestern Air</option>
	<option value="BJ"> Nouvelair Tunesie</option>
	<option value="1I"> Novair - Nova Airlines</option>
	<option value="L8"> Novosibirsk Airlines</option>
	<option value="NV"> NWT Air - Northwest Territorial Airways</option>
	<option value="UQ"> O'Connor Airlines - Mount Gambier Airline</option>
	<option value="5K"> Odessa Airlines</option>
	<option value="4B"> Olson Air Service</option>
	<option value="OL"> OLT - Ostfriesische Lufttransport</option>
	<option value="OA"> Olympic Airways</option>
	<option value="WY"> Oman Aviation</option>
	<option value="RS"> Oman Royal Flight</option>
	<option value="8Q"> Onur Air</option>
	<option value="RF"> Ord air Charter</option>
	<option value="R2"> Orenburg Avia</option>
	<option value="OX"> Orient Thai Airlines</option>
	<option value="QO"> Origin Pacific Airways</option>
	<option value="BL"> Pacific Aiirlines</option>
	<option value="GX"> Pacific Airways Corporation - Pacificair</option>
	<option value="8P"> Pacific Coastal Airways</option>
	<option value="9J"> Pacific Island Aviation</option>
	<option value="PF"> Palestinian Airlines</option>
	<option value="7E"> Panagra Airways</option>
	<option value="PV"> Panair</option>
	<option value="P8"> Pantanal - Linhas Aereas Sul Matogrossenses</option>
	<option value="HI"> Papillon Grand Canyon Helicopters</option>
	<option value="FP"> Par Avion</option>
	<option value="Y8"> Passaredo Transportes Aereos</option>
	<option value="QH"> Pel Air</option>
	<option value="9P"> Pelangi Airways</option>
	<option value="PD"> Pem Air</option>
	<option value="5P"> Pena Transportes Aereos - PENTA</option>
	<option value="KS"> Penair - Peninsula Airways</option>
	<option value="PR"> Philippines - Philippine Air Lines</option>
	<option value="PK"> PIA - Pakistan International Airlines</option>
	<option value="2Q"> PINAIR Panamian International</option>
	<option value="PU"> PLUNA</option>
	<option value="PO"> Polar Air Cargo</option>
	<option value="PH"> Polynesian Airline of Samoa</option>
	<option value="NI"> Portugalia</option>
	<option value="PW"> Precision Air Services</option>
	<option value="DK"> Premiar</option>
	<option value="P3"> Premier Trans Aire</option>
	<option value="TO"> President Airlines</option>
	<option value="P9"> Pro Air</option>
	<option value="Z3"> Pro Mech Air</option>
	<option value="YS"> Proteus Air System</option>
	<option value="AG"> Provincial Airlines</option>
	<option value="Z8"> Pulkovo Avia</option>
	<option value="QF"> Qantas</option>
	<option value="QR"> Qatar Airways</option>
	<option value="7Q"> Queen Air</option>
	<option value="QD"> Qwestair</option>
	<option value="RW"> RAS Fluggesellschaft</option>
	<option value="RX"> Redwing Airways</option>
	<option value="RV"> Reeve Aleutian Airways - RAA</option>
	<option value="7S"> Region Air</option>
	<option value="QT"> Regional Air</option>
	<option value="FN"> Regional Airlines</option>
	<option value="VM"> Regional Airlines</option>
	<option value="XG"> Regional Lineas Aereas</option>
	<option value="RH"> Regionnair</option>
	<option value="R8"> Reguljair</option>
	<option value="QQ"> Reno Air</option>
	<option value="WE"> Rheintalflug</option>
	<option value="GV"> Riga Airlines - RiAir</option>
	<option value="SL"> Rio Sul</option>
	<option value="Q3"> ROAN Air</option>
	<option value="WQ"> Romavia</option>
	<option value="6J"> Roots Air</option>
	<option value="5R"> Rover Airways International</option>
	<option value="VJ"> Royal Air Cambodge</option>
	<option value="AT"> Royal Air Maroc</option>
	<option value="QN"> Royal Airlines</option>
	<option value="BI"> Royal Brunei Airlines</option>
	<option value="RJ"> Royal Jordanian</option>
	<option value="RA"> Royal Nepal Airlines</option>
	<option value="WR"> Royal Tongan Airlines ( Friendly Island Airways)</option>
	<option value="2Q"> Rusavia Int'l Aviatransport</option>
	<option value="1I"> Ryan International Airlines</option>
	<option value="FR"> Ryanair</option>
	<option value="4Z"> SA Airlink - Midlands Aviation</option>
	<option value="Y2"> SA Alliance</option>
	<option value="SN"> Sabena</option>
	<option value="TJ"> Sabre Airways</option>
	<option value="EH"> SAETA - Sociedad Ecuatoriana de Aereos</option>
	<option value="FA"> Safair</option>
	<option value="S2"> Sahara Airlines</option>
	<option value="PV"> Saint Barth Commuter</option>
	<option value="K7"> Sakha Avia</option>
	<option value="HZ"> Sakhalinskie Aviatrassy - SAT</option>
	<option value="MM"> SAM - Sociedad Aeonautica de Medellin</option>
	<option value="MM"> SAM - Sociedad Aeronautica de Medellin</option>
	<option value="E5"> Samara Airlines</option>
	<option value="SE"> Samoa Air</option>
	<option value="WB"> SAN - Servicios Aereos Nationales</option>
	<option value="S3"> San Air Company</option>
	<option value="RZ"> SANSA - Servicios Aereos Nacionales SA</option>
	<option value="BJ"> Santa Barbara Airlines</option>
	<option value="SK"> SAS - Scandinavian Airlines System</option>
	<option value="SP"> SATA Air Acores</option>
	<option value="S4"> SATA International</option>
	<option value="SV" selected> Saudi Arabian Airlines</option>
	<option value="W7"> Sayakhat</option>
	<option value="3L"> Scenic Air</option>
	<option value="YR"> Scenic Airlines</option>
	<option value="AW"> Schreiner Airways</option>
	<option value="BB"> Seaborne Aviation</option>
	<option value="SG"> Sempati Air Transport</option>
	<option value="VC"> Servivensa - Empresa Servicios Avensa SA</option>
	<option value="NL"> Shaheen Air International</option>
	<option value="FM"> Shanghai Airlines</option>
	<option value="8C"> Shanxi Airlines</option>
	<option value="4G"> Shenzen Airlines</option>
	<option value="OB"> Shepparton Airlines</option>
	<option value="7Q"> Shorouk Air</option>
	<option value="CQ"> Shunshine Express Airlines</option>
	<option value="3S"> Shuswap Flight Centre</option>
	<option value="S5"> Shuttle America</option>
	<option value="5M"> Sibaviatrans</option>
	<option value="S7"> Siberia Airlines</option>
	<option value="3U"> Sichuan Airlines</option>
	<option value="LJ"> Sierra National Airlines</option>
	<option value="SI"> Sierra Pacific Airlines</option>
	<option value="MI"> Silkair</option>
	<option value="SQ"> Singapore Airlines</option>
	<option value="S9"> SK Air</option>
	<option value="5Q"> Skargardsflyg</option>
	<option value="SY"> Skippers Aviation</option>
	<option value="2E"> Sky Cabs</option>
	<option value="1I"> Sky Trek International Airlines</option>
	<option value="RU"> Skyking</option>
	<option value="BC"> Skymark Airlines</option>
	<option value="NP"> Skytrans</option>
	<option value="K9"> Skyward Aviation</option>
	<option value="AL"> Skyway Airlines / Midwest Express Connection</option>
	<option value="JZ"> Skyways</option>
	<option value="OO"> Skywest Airlines</option>
	<option value="YT"> Skywest Airlines</option>
	<option value="6Q"> Slovak Airlines - Slovenske Aerolinie</option>
	<option value="Q7"> Sobelair</option>
	<option value="IE"> Solomon Airlines</option>
	<option value="SA"> South African Airways - SAA</option>
	<option value="YB"> South African Express Airways</option>
	<option value="XE"> SouthCentral Air</option>
	<option value="A4"> Southern Winds</option>
	<option value="WN"> Southwest Airlines</option>
	<option value="JK"> Spanair</option>
	<option value="C7"> Special Cargo Airlines</option>
	<option value="NK"> Spirit Airlines</option>
	<option value="FS"> STAF - Servicios de Transportes Aereos Fueguino</option>
	<option value="2R"> Star Airlines</option>
	<option value="2N"> Starwelt Airways</option>
	<option value="R4"> State Transport Company of Russia</option>
	<option value="CB"> Suckling Airways</option>
	<option value="SD"> Sudan Airways</option>
	<option value="BV"> Sun Air</option>
	<option value="EZ"> Sun Air of Scandinavia</option>
	<option value="SY"> Sun Country Airlines</option>
	<option value="XQ"> Sun Express</option>
	<option value="PI"> Sunflower Airlines</option>
	<option value="JX"> Sunjet International Airlines</option>
	<option value="OQ"> Sunrise Airlines</option>
	<option value="SM"> Sunworld International Airways</option>
	<option value="AB"> Superior Aviation</option>
	<option value="PY"> Surinam Airways / SLM </option>
	<option value="SI"> Svea Flyg</option>
	<option value="ZC"> Swazi Airlink</option>
	<option value="HJ"> Swedeways Air Lines</option>
	<option value="RQ"> Swiss Wings</option>
	<option value="SR"> Swissair</option>
	<option value="RB"> Syrianair - Syrian Arab Airlines</option>
	<option value="DT"> TAAG - Linhas Aereas de Angola - Angola Airlines</option>
	<option value="TA"> TACA International Airlines</option>
	<option value="VR"> TACV - Cabo Verde Airlines</option>
	<option value="GD"> TAESA - Transportes Aereos Ejecutivos SA</option>
	<option value="FP"> TAG Aviation</option>
	<option value="JJ"> TAM - Transportes Aereos Meridionais</option>
	<option value="KK"> TAM - Transportes Aereos Regionais</option>
	<option value="OF"> TAM - Travaux Aeriens de Madagascar</option>
	<option value="EQ"> TAME - Transportes Aereos Militares Ecuatoriana</option>
	<option value="QT"> TAMPA Colombia</option>
	<option value="T8"> TAN - Transportes Aereos Neuquen</option>
	<option value="4E"> Tanana Air Services</option>
	<option value="TP"> TAP Air Portugal</option>
	<option value="K3"> Taquan Air Service</option>
	<option value="RQ"> TAROM - Transporturile Aerienne Romane</option>
	<option value="9X"> Tasawi Air Service</option>
	<option value="PQ"> Tashkent Aircraft Production Corporation</option>
	<option value="QS"> Tatra Air</option>
	<option value="4U"> TAVAJ - Transportes Aereos Regulares</option>
	<option value="T6"> Tavrey Aircompany</option>
	<option value="ZJ"> Teddy Air</option>
	<option value="FC"> Tempelhoff Express Airlines - TEX</option>
	<option value="UZ"> Tesis</option>
	<option value="2Y"> Thai Air Cargo</option>
	<option value="TG"> Thai Airways International</option>
	<option value="TL"> TMA - Trans Mediterranean Airlines</option>
	<option value="TI"> Tolair Services</option>
	<option value="FF"> Tower Air</option>
	<option value="WI"> Trade Winds Airlines</option>
	<option value="P6"> Trans Air</option>
	<option value="ES"> Trans America Peru</option>
	<option value="T7"> Trans Asian Airlines</option>
	<option value="UE"> Trans European Airlines</option>
	<option value="5B"> Trans International Express</option>
	<option value="9N"> Trans States Airlines</option>
	<option value="6N"> Trans Travel Airlines - TTA</option>
	<option value="TW"> Trans World Airlines - TWA</option>
	<option value="UN"> Transaero Airlines</option>
	<option value="GE"> Transasia Airways</option>
	<option value="HV"> Transavia Airlines</option>
	<option value="AL"> TransAvia Export</option>
	<option value="TR"> Transbrasil</option>
	<option value="DZ"> Transcaraibes Air  International</option>
	<option value="T4"> Transeast Airlines</option>
	<option value="T9"> Transmeridian Airlines</option>
	<option value="TH"> Transmile Air Services</option>
	<option value="BH"> Transstate Airlines</option>
	<option value="U3"> Travelair</option>
	<option value="PM"> Tropic Air</option>
	<option value="TU"> Tunisair</option>
	<option value="UG"> Tunisinter</option>
	<option value="3T"> Turanair</option>
	<option value="TK"> Turkish Airlines</option>
	<option value="T5"> Turkmenistan Airlines - Turkmenhavayollari</option>
	<option value="QW"> Turks and Caicos Airways</option>
	<option value="KT"> Turtle Airways</option>
	<option value="VO"> Tyrolean Airways</option>
	<option value="7M"> Tyumen Airlines</option>
	<option value="P2"> TyumenAviaTrans</option>
	<option value="WI"> U Land Airlines</option>
	<option value="QU"> Uganda Airlines</option>
	<option value="PS"> Ukraine International Airlines</option>
	<option value="F2"> UNA - Southern Independent Air Company</option>
	<option value="B7"> UNI Air</option>
	<option value="UA"> United Airlines</option>
	<option value="ZK"> United Express / Great Lakes Airlines</option>
	<option value="ZW"> United Express/Air Wisconsin</option>
	<option value="DH"> United Express/Atlantic Coast Airlines</option>
	<option value="9N"> United Express/Trans States Airlines</option>
	<option value="U2"> United Express/United Feeder Services</option>
	<option value="UV"> Universal Airways</option>
	<option value="5X"> UPS - United Parcel Service</option>
	<option value="U6"> Ural Airlines - Uralskie Avialinii</option>
	<option value="US"> US Airways</option>
	<option value="US"> US Airways Express</option>
	<option value="ZV"> US Airways Express/Air Midwest</option>
	<option value="US"> US Airways Express/Allegheny Commuter Airlines</option>
	<option value="US"> US Airways Express/Chautauqua Airlines</option>
	<option value="US"> US Airways Express/Piedmont Airlines</option>
	<option value="TB"> US Airways Shuttle</option>
	<option value="U7"> USA Jet Airlines</option>
	<option value="HY"> Uzbekistan Airways</option>
	<option value="T9"> V-Air - Varmlandsflyg</option>
	<option value="NJ"> Vanguard Airlines</option>
	<option value="RG"> Varig</option>
	<option value="VP"> VASP</option>
	<option value="VL"> VIA - Air VIA Bulgarian Airways</option>
	<option value="VI"> Vieques Air Link</option>
	<option value="VN"> Vietnam Airlines</option>
	<option value="9V"> Vip Air</option>
	<option value="VS"> Virgin Atlantic</option>
	<option value="TV"> Virgin Express</option>
	<option value="FV"> Viva Air</option>
	<option value="XF"> Vladivostok Air</option>
	<option value="VG"> VLM - Vlaamse Luchtvaart Maatschappij</option>
	<option value="V5"> Vnukovo Airlines</option>
	<option value="OP"> Volare Air transport</option>
	<option value="8D"> Volare Airlines</option>
	<option value="F7"> Volare Ukraine</option>
	<option value="G6"> Volga Airlines</option>
	<option value="VI"> Volga Dnepr Airlines</option>
	<option value="ZT"> Voronezh Avia</option>
	<option value="4V"> Voyageur Airways</option>
	<option value="2W"> Wairapa Airlines - Pacific Midland Airlines</option>
	<option value="4W"> Warbelow's Air Ventures</option>
	<option value="WG"> Wasaya Airways</option>
	<option value="2W"> Welcome Air</option>
	<option value="8O"> West Coast Air</option>
	<option value="7Y"> West Isle Air</option>
	<option value="OE"> Westair</option>
	<option value="WZ"> Western Air Freight</option>
	<option value="EM"> Western Airlines</option>
	<option value="M3"> Westjet Airlines</option>
	<option value="WW"> Whyalla Airlines</option>
	<option value="WF"> Wideroe - Wideroe's Flyveselskap</option>
	<option value="WM"> Winair - Windward Island Airways International</option>
	<option value="K5"> Wings of Alaska</option>
	<option value="KN"> Winnport Air Cargo</option>
	<option value="WO"> World Airways</option>
	<option value="8V"> Wright Air Service</option>
	<option value="MF"> Xiamen Airlines</option>
	<option value="ST"> Yanda Airlines</option>
	<option value="HK"> Yangon Airways</option>
	<option value="IY"> Yemenia - Yemen Airways</option>
	<option value="4Y"> Yute Air Alaska</option>
	<option value="Z7"> Zimbabwe Express Airlines</option>
	<option value="C4"> Zimex Aviation</option>
	<option value="NAS"> Fly Nas</option>
	<option value="None" selected="selected" >None</option>                        
</select>